name: bv_front_app
description: "Bidvest App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase: ^9.0.3
  cloud_firestore: ^5.1.0
  animations: ^2.0.11
  responsive_builder: ^0.7.1
  google_fonts: ^4.0.4
  http: ^0.13.0
  firebase_auth: ^5.1.2
  get_it: ^7.7.0
  fluttertoast: ^8.2.6
  flutter_analog_clock: ^1.0.3
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  page_transition: ^2.1.0
  accordion: ^2.6.0
  intl: ^0.19.0
  badges: ^3.1.2
  custom_rating_bar: ^3.0.0

  firebase_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

