// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApMsjLVjhZlLK8DmhYNTvoJoyR8uYIWwE',
    appId: '1:950142618932:web:eda9a8c304a9e10058e961',
    messagingSenderId: '950142618932',
    projectId: 'bidvest-33-8eaf4',
    authDomain: 'bidvest-33-8eaf4.firebaseapp.com',
    storageBucket: 'bidvest-33-8eaf4.appspot.com',
    measurementId: 'G-G0HWHB5MMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVVbNw3A3G86JqghV8fR5t1jaznKdVkY',
    appId: '1:950142618932:android:20e64c0a1b22c5db58e961',
    messagingSenderId: '950142618932',
    projectId: 'bidvest-33-8eaf4',
    storageBucket: 'bidvest-33-8eaf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYVB7POoU8U83WtLnmTFBE_-6jObbDEsg',
    appId: '1:950142618932:ios:66ced8b6a10f01c258e961',
    messagingSenderId: '950142618932',
    projectId: 'bidvest-33-8eaf4',
    storageBucket: 'bidvest-33-8eaf4.appspot.com',
    iosBundleId: 'com.boha.bidvestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYVB7POoU8U83WtLnmTFBE_-6jObbDEsg',
    appId: '1:950142618932:ios:bfb0ead2d85873eb58e961',
    messagingSenderId: '950142618932',
    projectId: 'bidvest-33-8eaf4',
    storageBucket: 'bidvest-33-8eaf4.appspot.com',
    iosBundleId: 'com.boha.bvFrontApp.RunnerTests',
  );
}
